Repository vue-macros/vue-macros, pull requests merged in 2024-08, with the labels that each got.

#757 feat(config): add script-sfc option
  .changeset/blue-tomatoes-marry.md
Labels: enhancement, size:XS, lgtm

#759 feat(jsx-directive): use vSlots prop as component's slots
  .changeset/gorgeous-snails-help.md
  packages/jsx-directive/src/core/v-slot.ts
  packages/jsx-directive/tests/__snapshots__/v-slot.test.ts.snap
  packages/volar/src/jsx-directive.ts
  packages/volar/src/jsx-directive/context.ts
  packages/volar/src/jsx-directive/v-slot.ts
Labels: enhancement, size:M

#760 feat(jsx-directive): decouple from vue
  .changeset/two-zoos-eat.md
  packages/common/src/dep.ts
  packages/jsx-directive/package.json
  packages/jsx-directive/src/core/index.ts
  packages/jsx-directive/src/core/v-for.ts
  packages/jsx-directive/src/core/v-html.ts
  packages/jsx-directive/src/core/v-if.ts
  packages/jsx-directive/src/core/v-memo.ts
  packages/jsx-directive/src/core/v-model.ts
  packages/jsx-directive/src/core/v-on.ts
  packages/jsx-directive/src/core/v-slot.ts
  packages/jsx-directive/src/helpers.ts
  packages/jsx-directive/src/index.ts
  pnpm-lock.yaml
Labels: enhancement, size:L, lgtm

#763 feat(volar): compatible with old usage
  .changeset/real-trees-retire.md
  packages/volar/src/boolean-prop.ts
  packages/volar/src/common.ts
  packages/volar/src/define-emit.ts
  packages/volar/src/define-generic.ts
  packages/volar/src/define-models.ts
  packages/volar/src/define-options.ts
  packages/volar/src/define-prop.ts
  packages/volar/src/define-props-refs.ts
  packages/volar/src/define-props.ts
  packages/volar/src/define-slots.ts
  packages/volar/src/export-expose.ts
  packages/volar/src/export-props.ts
  packages/volar/src/export-render.ts
  packages/volar/src/index.ts
  packages/volar/src/jsx-directive.ts
  packages/volar/src/script-lang.ts
  packages/volar/src/script-sfc.ts
  packages/volar/src/setup-jsdoc.ts
  packages/volar/src/setup-sfc.ts
  packages/volar/src/short-bind.ts
  packages/volar/src/short-vmodel.ts
  packages/volar/src/template-ref.ts
Labels: volar, size:L

#752 feat: enable `noCheck` for dts
  docs/.vitepress/theme/Layout.vue
  package.json
  packages/volar/src/export-expose.ts
  playground/vue2/package.json
  playground/vue3/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tsconfig.lib.json
  tsup.config.ts
Labels: enhancement, size:M

#778 fix(docs): wrap team members on small screen
  docs/.vitepress/components/HomePage.vue
Labels: documentation, size:XS, lgtm
