Repository vue-macros/vue-macros, pull requests merged in 2024-06, with the labels that each got.

#695 feat(docs): add read enhanced plugins
  docs/.vitepress/theme/Layout.vue
  docs/.vitepress/theme/index.ts
  docs/interactive/index.md
  docs/package.json
  docs/vite.config.ts
  pnpm-lock.yaml
Labels: documentation, size:M, lgtm

#699 feat(boolean-prop): add support for negative prefix as false value
  .changeset/famous-houses-melt.md
  docs/features/boolean-prop.md
  docs/zh-CN/features/boolean-prop.md
  packages/boolean-prop/src/core/transformer.ts
  packages/boolean-prop/tests/__snapshots__/compiler.test.ts.snap
  packages/boolean-prop/tests/compiler.test.ts
Labels: enhancement, size:M, lgtm

#702 fix(volar/export-expose): add prefix semicolon to fix syntax errors
  .changeset/rude-bags-work.md
  packages/export-expose/tests/__snapshots__/fixtures.test.ts.snap
  packages/export-expose/tests/fixtures/basic.vue
  packages/volar/src/export-expose.ts
Labels: size:XS, lgtm

#701 feat(volar): introduce `boolean-prop`
  .changeset/hot-steaks-camp.md
  docs/features/boolean-prop.md
  docs/guide/bundler-integration.md
  docs/zh-CN/features/boolean-prop.md
  docs/zh-CN/guide/bundler-integration.md
  packages/boolean-prop/src/core/transformer.ts
  packages/boolean-prop/tests/__snapshots__/compiler.test.ts.snap
  packages/boolean-prop/tests/__snapshots__/fixtures.test.ts.snap
  packages/boolean-prop/tests/fixtures/basic.vue
  packages/volar/package.json
  packages/volar/src/boolean-prop.ts
  playground/vue3/src/examples/boolean-prop/child.vue
  playground/vue3/src/examples/boolean-prop/index.vue
  playground/vue3/tsconfig.json
  pnpm-lock.yaml
  tsconfig.fixture.json
Labels: enhancement, volar, size:M, lgtm

#705 fix(volar): add await before the import function
  packages/volar/src/common.ts
Labels: volar, size:XS, lgtm

#706 feat(docs): support twoslash
  docs/.vitepress/config.ts
  docs/.vitepress/theme/index.ts
  docs/features/better-define.md
  docs/features/boolean-prop.md
  docs/features/export-expose.md
  docs/features/export-props.md
  docs/features/hoist-static.md
  docs/features/jsx-directive.md
  docs/features/reactivity-transform.md
  docs/features/short-bind.md
  docs/macros/chain-call.md
  docs/macros/define-emit.md
  docs/macros/define-models.md
  docs/macros/define-options.md
  docs/macros/define-prop.md
  docs/macros/define-props-refs.md
  docs/macros/define-props.md
  docs/macros/define-render.md
  docs/macros/define-slots.md
  docs/macros/setup-component.md
  docs/macros/setup-sfc.md
  docs/macros/short-emits.md
  docs/package.json
  docs/zh-CN/features/better-define.md
  docs/zh-CN/features/boolean-prop.md
  docs/zh-CN/features/export-expose.md
  docs/zh-CN/features/export-props.md
  docs/zh-CN/features/hoist-static.md
  docs/zh-CN/features/jsx-directive.md
  docs/zh-CN/features/reactivity-transform.md
  docs/zh-CN/features/short-bind.md
  docs/zh-CN/macros/chain-call.md
  docs/zh-CN/macros/define-emit.md
  docs/zh-CN/macros/define-models.md
  docs/zh-CN/macros/define-options.md
  docs/zh-CN/macros/define-prop.md
  docs/zh-CN/macros/define-props-refs.md
  docs/zh-CN/macros/define-props.md
  docs/zh-CN/macros/define-render.md
  docs/zh-CN/macros/define-slots.md
  docs/zh-CN/macros/setup-component.md
  docs/zh-CN/macros/setup-sfc.md
  docs/zh-CN/macros/short-emits.md
  eslint.config.js
  packages/volar/package.json
  pnpm-lock.yaml
Labels: documentation, size:XXL

#707 feat(volar/jsx-directive): support keyboard event with keys
  .changeset/shaggy-cougars-film.md
  packages/jsx-directive/src/core/v-on.ts
  packages/jsx-directive/tests/__snapshots__/v-on.test.ts.snap
  packages/jsx-directive/tests/fixtures/v-on/child.vue
Labels: enhancement, volar, size:M

#708 feat(volar/jsx-directive): allow duplicate events with modifiers
  .changeset/neat-teachers-greet.md
  packages/jsx-directive/tests/__snapshots__/v-on.test.ts.snap
  packages/jsx-directive/tests/fixtures/v-on/child.vue
  packages/jsx-directive/tests/fixtures/v-on/index.vue
  packages/volar/src/jsx-directive/v-on.ts
Labels: enhancement, size:M

#714 feat(volar/jsx-directive): remove camelCase events support
  .changeset/ten-onions-sniff.md
  packages/volar/src/jsx-directive/index.ts
Labels: enhancement, size:S
